version: '3'

services:
  db: 
    image: mysql:8
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/volume:/var/lib/mysql
      # - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=vollmed_api
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 5